url: "https://Wang_HongWei_MathPage.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "WangHongWei_AcademicPage" # the name of your site, e.g. ACME Corp.
description: "WangHongWei's Math Homepage"
email:"1972396871@qq.com"
github_username:WangHongWei-AcademicPage
