# 网站设置
url: "https://WangHongWei-AcademicPage.github.io"
baseurl: "" 
title: "Hongwei Wang" 
description: >-
  Undergraduate student in Pure Mathematics at Xi'an Jiaotong-Liverpool University, with 
  focus in algebraic topology, homotopy theory, homotopy type theory, and formal verification of 
  mathematics using Lean theorem prover.


# 你的信息
name: "Hongwei Wang" 
email: "1972396871@qq.com"
github_username: WangHongWei-AcademicPage

# 构建设置
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 其他设置（暂时保持原样）
twitter_username: ""
google_scholar_id: ""
linkedin_username: ""
medium_username: ""
